### ISSUE TITLE
New contribute.json test has nothing to do with security?

### ISSUE THREAD

**Issue by jeffoneill** [mozilla/http-observatory-website#137]
I recently discovered the Observatory site, and it is amazing!  Kudos to a job well done.

I just went back today and discovered that I am now failing a "contribute.json" test.  After reading about this test at https://www.contributejson.org/, it seems this test has nothing to do with security.  

The closest thing to security seems to be that it helps people to submit bug reports, but to impose this standard for submitting bug reports doesn't help with website security.  There are many suitable ways for submitting bug reports.

Please consider removing this test or explaining its relevance to security.

**Comment by floatingatoll** [comment]
What URL is failing this test? Do you have a contribute.json file at all?

**Comment by jeffoneill** [comment]
I don't have a contribute.json file.  The site is https://www.patentbots.com/

**Comment by anelson425** [comment]
Is there any additional info on this? I can't find relevance to web security either. We recently started scanning some sites with observatory and teams are being hit with 404's about missing contribute.json.

**Comment by floatingatoll** [comment]
A missing Contribute.json should not penalize your site score unless you're
a Mozilla-operated site. If your site is receiving a negative score, rather
than a zero score, please let us know your site URL so that we can find out
why it's mistakenly considered a Mozilla site and resolve that issue.

HTTP Observatory will generate many, many 404s on the sites it checks, as
part of testing for various interesting properties of the sites in question
— for example, crossdomain.xml. Checks for contribute.json will be one such
potential 404. If this a significant issue for your sites, you could fork
the scanner code (see README.md) and run local scans yourself with the
contribute.json checks removed.

**Comment by anelson425** [comment]
Thanks for the response. We aren't seeing penalties associating to this, just developers asking whats going on with the scanner and why their servers are being hit with requests for crossdomain.xml, contribute.json and clientaccesspolicy.xml.

My question really comes down to whether the scanner should include these or not. I was under the impression that the scanner was scanning for security specific concerns but I do not see how these are associated with security. If these are not security related, do they really belong here?

**Comment by floatingatoll** [comment]
A certain poorly-constructed crossdomain.xml or clientaccesspolicy.xml can,
if I remember correctly, have a -50 penalty to score due to how severely it
can impact security. Some sites scanned by Observatory receive that
penalty, and so reporting the security hazard helps those site operators
who are affected understand that they are at risk and respond as they see
fit.

Contribute.json earns a bonus when it contains security contact information
for non-Mozilla sites, and a penalty when it is absent from Mozilla sites.
It's currently one of few — if not only — standard for advertising security
contacts for a website. It isn't necessarily popular, but until a
replacement standard is developed that meets the specific use case of
"machine-parseable security contact information", it's likely to stay for
the foreseable future.

**Comment by april** [comment]
The website doesn't show the contribute.json tests and the command line tools shouldn't penalize for it at all:

https://observatory.mozilla.org/analyze/www.patentbots.com

Where are you seeing it show up in your tests?
