### ISSUE TITLE
HSTS redirection and base domain issue / feedback

### ISSUE THREAD

**Issue by githubhero** [mozilla/http-observatory-website#170]
Hello, I tested a website at Mozilla Observatory and found HSTS was perfectly ok.

In the MO faq, I found:

> (Redirection) What is the redirection test assessing?
> 
> This test is checking whether your web server is making its initial redirection is from HTTP to HTTPS and on the same hostname before doing any further redirections. This allows the HTTP Strict Transport Security (HSTS) header to be applied properly.
> 
> For example, this redirection order is correct:
> http://example.com → https://example.com → https://www.example.com.

My redirection is absolutely correct.

BUT, when I test the eligibility of my website at https://hstspreload.org, I get an error "Response error: No HSTS header is present on the response".

The header is PRESENT but it is not present in the "base domain" (example.com): it is present in the following redirects.

Now: if the HSTS should be present in the base domain, I think MO tests should consider this. Instead, I get higher score, even if I added it to redirects and not to the base domain (not for lazyness: my cheap webhosting doesn't let me control the base domain as I would).

If HSTS shouldn't be present, hstspreload.org website is wrong.

**Comment by floatingatoll** [comment]
May we know what domain you’re scanning so that we can verify that
everything is working correctly with the scans? HSTS Preload could have
different requirements, but it’s odd that you would get a positive score
and not meet them.

**Comment by githubhero** [comment]
Well, of course, but not in public.   :-)

**Comment by floatingatoll** [comment]
Email me? Atoll at Mozilla dot com.

**Comment by githubhero** [comment]
Perfect, I send you an email in a couple of minutes

**Comment by floatingatoll** [comment]
Received, I’ll report back soon!

**Comment by floatingatoll** [comment]
Given your private domain name which I will hereby refer to as "example.com",
I found the following issue, which is not detected by the Observatory
scanner:

http://example.com/ -> https://example.com/ — This redirect is a 302, which
is perhaps not ideal, but is otherwise fine. It is _correctly_ missing the
HSTS header, as HSTS is inappropriate for an http:// response.

https://example.com/ -> https://www.example.com/ — This redirect is
_incorrectly_ missing the HSTS header, as HSTS must be included on _all_
https:// responses.

Since you're using Apache, you'll find the following line extremely helpful
for your non-www-to-www virtualhost redirect:

Header always set Strict-Transport-Security "max-age=...etc..."

I believe the "always" works out to be necessary to ensure that it's set
when using Redirect / or RewriteRule.

Try that and see if it helps?

**Comment by floatingatoll** [comment]
@april also — is this a scanner bug?

**Comment by githubhero** [comment]
@floatingatoll 

right after posting here about my "cheap hosting", I found a very useful comment by MrWhite in the end of this discussion: https://serverfault.com/questions/930368/hsts-and-double-redirect 

So, probably, the htaccess file where I set the header is missing "always", as you pointed out (I've changed it, you can freely try).

Anyway, my post here was about MO making me happily pass any test even if I set my HSTS the wrong way   :-)

**Comment by april** [comment]
Looking at this, I think you're right in that the HSTS test should probably check each step along the way, instead of just looking for HSTS on the final location.

The logic does get pretty complicated though, like if you did:

https://foo.com/ (with HSTS) -> https://foo.com/bar (no HSTS) -> https://foo.com/baz, then that is weird but maybe fine?

Anyways, thanks for finding this bug. Much appreciated.

**Comment by githubhero** [comment]
@april you're welcome   :-)  I found the bug because I had one on my end!   :-)

It would be interesting to know how _hstspreload_ website developed their tests:
anyway, in the fourth tab of the MO website, I've seen MO loads their results too.

Now, without any further implementation (=logic), couldn't MO simply request data from their website and then score points based on the result of that request?

**Comment by githubhero** [comment]
@april mmm, ok   :-)

**Comment by floatingatoll** [comment]
To me — https://foo.com/bar (no HSTS) is not fine, because HSTS should be
set on _all_ HTTPS responses, without exception, and so any exceptions
should result in alarm.

**Comment by githubhero** [comment]
@floatingatoll From the _hstspreload_ website:

> If you are serving an additional redirect from your HTTPS site, that redirect must still have the HSTS header (rather than the page it redirects to)

**Comment by floatingatoll** [comment]
Yes, that's the assertion I'm making as well. I'll state it more simply:

All https:// responses must contain Strict-Transport-Security, regardless
of whether they're a redirect or not.

So given a redirect from http:// to https://, the https:// response must
include Strict-Transport-Headers.

And given a redirect from http:// to https:// to https://, both https://
responses must include Strict-Transport-Headers.

**Comment by githubhero** [comment]
@floatingatoll There could be other things to test too: for example, tests with max-age, includeSubDomains and preload

**Comment by floatingatoll** [comment]
You get a score boost for preload usually a few weeks after being added to
the preload list.

Max age is scored differently already at, I believe, above/under the 6
month threshold.

Includesubdomains is not safe to recommend without careful study of each
person’s scenario. We can’t use it on certain Mozilla domains, for example,
because there are legitimate needs for non-HTTPS. Since these values are
cached for 6+ months, it would be particularly traumatic for anyone we
encourage to try it that then discovers they shouldn’t have the hard way.

**Comment by githubhero** [comment]
@floatingatoll Ok for the "legitimate needs', but isn't there any security risk (cookie attacks, etc.)?

**Comment by Darkspirit** [comment]
> We can’t use it on certain Mozilla domains, for example, because there are legitimate needs for non-HTTPS.

Never. And detectportal.firefox.com should maybe get a negative and non-expiring preload entry in Firefox.

**Comment by githubhero** [comment]
@Darkspirit What's the purpose of detectportal.firefox.com?

**Comment by floatingatoll** [comment]
I filed a scoring bug reflecting the HSTS issue discovered here, concluding the discussion here. Thanks everyone for providing input.

**Comment by Darkspirit** [comment]
@githubhero I don't exactly know how it works, but it might be like this: If http://detectportal.firefox.com/success.txt (pref: captivedetect.canonicalURL) doesn't return "sucess", Firefox replaces a certificate error page with a [different](https://blog.mozilla.org/wp-content/uploads/2017/03/52wifilogin-768x606.png) error page.

**Comment by april** [comment]
Yes, that's exactly what it's for.

It's to detect if you're stuck inside a captive wifi system, such as hotels. It makes a plain HTTP request there and if it doesn't get back OK then it assumes that you're trapped.

Instead of trying to get a negative and non-expiring entry for detectportal.firefox.com, the code inside Firefox that makes that request should simply ignore the HSTS setting for the domain.
