### ISSUE TITLE
Unhandled exception with invalid SameSite declaration

### ISSUE THREAD

**Issue by vinzv** [mozilla/http-observatory-website#176]
I'm trying to scan https://less.re but there is no reaction. When I tick "Force rescan..." the scan starts but immediately fails.

**Comment by floatingatoll** [comment]
I was able to scan many xxyyzz.re domains with longer names than this one,
but not this one, oddly.

**Comment by floatingatoll** [comment]
```
  File "/usr/local/lib/python3.6/site-packages/httpobs/scanner/analyzer/headers.py", line 336, in cookies
    if cookie._rest[key] is True or cookie._rest[key].strip().lower() == 'strict':
```

Introduced by d49ad05a5c09b3ea9c1f7695304d85521fcee0b6, triggered by:

`set-cookie: PHPSESSID=14kqgnsqfm5g3cgcgb592urig0; path=/; HttpOnly;SameSite;Secure`

@vinzv Thanks for the bug report! You should fix those `;` to be `; ` so that your header is valid, and that _should_ resolve the difficulty you're seeing with the Observatory as well as avoid any potential browser issues with the malformed header (the spaces are mandatory, as I understand it).

**Comment by floatingatoll** [comment]
I spoke too soon. You need to specify either `SameSite=Strict` or `SameSite=Lax`, not just `SameSite`.

**Comment by floatingatoll** [comment]
Moving this issue to the appropriate repository, as mozilla/http-observatory#369.
