### ISSUE TITLE
Reports my site as not redirecting to https when it absolutely does

### ISSUE THREAD

**Issue by TotallyInformation** [mozilla/http-observatory-website#201]
My site is it.knightnet.org.uk

If I type in "http://it.knightnet.org.uk" I am redirected correctly to https - indeed all of my resources are automatically redirected and Cloudflare enforces this for me.

So why is Observatory claiming it isn't happening?

**Comment by Nightfirecat** [comment]
I'm getting an HTTP 403 when trying to reach that site:

> ## Error 1020 (Ray ID: 4f98969c5e9dc981 • 2019-07-20 23:06:54 UTC)
> ### Access denied
> **What happened?**
>
> This website is using a security service to protect itself from online attacks.

```
$ curl -sI http://it.knightnet.org.uk
HTTP/1.1 403 Forbidden
Date: Sat, 20 Jul 2019 23:08:38 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Set-Cookie: __cfduid=de1a18343ba70c00da964294b8e7444d11563664118; expires=Sun, 19-Jul-20 23:08:38 GMT; path=/; domain=.knightnet.org.uk; HttpOnly; Secure
Cache-Control: max-age=15
Expires: Sat, 20 Jul 2019 23:08:53 GMT
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
Server: cloudflare
CF-RAY: 4f9899252f19799b-SEA
```

**Comment by TotallyInformation** [comment]
Weird - I'm getting this:

```
$ curl -sI http://it.knightnet.org.uk
HTTP/1.1 301 Moved Permanently
Date: Sun, 21 Jul 2019 00:06:07 GMT
Connection: keep-alive
Cache-Control: max-age=3600
Expires: Sun, 21 Jul 2019 01:06:07 GMT
Location: https://it.knightnet.org.uk/
X-Content-Type-Options: nosniff
Server: cloudflare
CF-RAY: 4f98ed586ab3ce13-LHR
```

**Comment by Nightfirecat** [comment]
Not that I'm aware of. This was just run from a residential IP, so I'd hope that's not the case.

**Comment by floatingatoll** [comment]
Cloudflare denied me access as well. It probably has an IP whitelist
configured.

**Comment by TotallyInformation** [comment]
Cloudflare settings:

![image](https://user-images.githubusercontent.com/1591850/61596492-5d7b9800-abfc-11e9-8881-4f489f6610ff.png)

![image](https://user-images.githubusercontent.com/1591850/61596498-6c624a80-abfc-11e9-9bc6-64b61aeebdf3.png)

![image](https://user-images.githubusercontent.com/1591850/61596501-7b48fd00-abfc-11e9-9db5-690ebdd095a6.png)

![image](https://user-images.githubusercontent.com/1591850/61596505-84d26500-abfc-11e9-91ea-7842c1a8324c.png)

SecurityHeaders.com results:

![image](https://user-images.githubusercontent.com/1591850/61596515-aaf80500-abfc-11e9-9e57-e788ee2a36c9.png)

Observatory Results:

![image](https://user-images.githubusercontent.com/1591850/61596541-db3fa380-abfc-11e9-8b0b-ac909c7cfd2a.png)

**Comment by floatingatoll** [comment]
SecurityHeaders is testing your HTTPS site, note the URL - and penalizing
you for http:// not being a redirect, which is what we’re all seeing as
well.

I recommend you contact CloudFlare support and ask them to help you
understand this error page from your HTTP site; below is the full CF “Ray
ID” 4fa00002ad5f1e69 output for their diagnostics, be sure to provide them
that ID. Additionally I recommend you use your browser’s network inspector
to confirm that when you enter the http:// URL into your browser it makes
any network request at all over http:// port 80, as HSTS testing may have
left cached “upgrade to https://“ remnants that you aren’t clearing.
Finally I recommend using the terminal command “curl -D -
http://it.knightnet.org.uk” so that you are absolutely certain that you’re
not being misled in any way about what’s being returned.

Unfortunately I don’t have any experience with these settings at Cloudflare
and will not be able to offer guidance on how to resolve this, but I’m
certain their support will be able to help if you ask.

Error 1020Ray ID: 4fa00002ad5f1e69 • 2019-07-21 20:42:12 UTCAccess denied

**Comment by april** [comment]
The site is simply giving me cloudflare errors, which is presumably why it's not redirecting to HTTPS. Either way, it seems to be consistent across services and not an Observatory bug.
