### ISSUE TITLE
Observatory claims CSP cannot be parsed.

### ISSUE THREAD

**Issue by iBeizsley** [mozilla/http-observatory-website#211]
I'm pretty certain my CSP _is_ valid, and Firefox, Chrome, Google's CSP validator, and numerous other scanners seem to think it's A-OK.

Observatory, however, fails to parse it.

https://observatory.mozilla.org/analyze/beizsley.com

CSP content, according to observatory (which is correct) is:
```
default-src 'none';
font-src https://fonts.gstatic.com;
style-src 'self' https://fonts.googleapis.com;
img-src 'self';
frame-ancestors 'none';
base-uri 'self';
form-action 'self';
script-src https: 'self' 'strict-dynamic'
```
(Formatting tweaked for readability here)

Also reported the same problem with a `;` at the end.

**Comment by floatingatoll** [comment]
Evaluating your site’s CSP rules warns about script-src being invalid due
to the combination of strict-dynamic without nonce/hash and with
https:/self. You can see these at https://csp-evaluator.withgoogle.com.

It could be possible that the Observatory considers the CSP invalid as a
result.


   - 'strict-dynamic' without a CSP nonce/hash will block all scripts.


   -
   - 'https:' Because of strict-dynamic this entry is ignored in CSP3 and
   above


   -
   - 'self' Because of strict-dynamic this entry is ignored in CSP3 and
   above

**Comment by iBeizsley** [comment]
Fair enough; I assumed it wasn't using the Google validator directly as it's an `information` level 'problem'.

I'll go ahead and close this issue (assuming `information` level things are intended to invalidate the CSP in observatory) and re-open it if, once I've got a script w/ a csp-included nonce in the site, the problem still exists.
