### ISSUE TITLE
Possible scoring issue on Mozilla Observatory

### ISSUE THREAD

**Issue by mktl73** [mozilla/http-observatory-website#215]
Steps to reproduce:

I launched a scan on server eurocontrol.int and get a "85/100" score
https://observatory.mozilla.org/analyze/eurocontrol.int

Actual results:

If I understand well, the baseline score is 100 so I should have:
100 - 10 + 5 +5 - 5 +5 = 100 but I only get 85 (A-)
I have the impression that I receive the penalties but not the bonuses

Expected results:

I believe the score should be 100 and therefore the grade A+

**Comment by floatingatoll** [comment]
Bonuses are only incorporated into the final score when there are no
penalties, to emphasize the necessity of considering issues that are
serious enough to have a negative score attached.

For example, in this specific score result, it’s very important to resolve
the “not all external scripts are loaded over HTTPS” issue, as otherwise
your site’s code can be modified in transit to the user without your
consent. (This can usually be resolved easily by replacing <script
src=http:// and <script src=// with <script src=https:// anywhere that they
are present.)

**Comment by mktl73** [comment]
Thanks but are you talking "per test" or global?
I fully agree that this is true per test but, for example, the +5 for cookies are they taken into account or not in the final score?
I created this case because the service was not behaving like this a few days ago (the score was 105/100 and A+).
I was wondering if this is a bug, a change in the baseline score or a new way of scoring (must have no penalties at all).

**Comment by floatingatoll** [comment]
Tests which are internally marked as ‘extra credit’ (scores ranging 0..N,
with no negative penalty) will not have their +N applied if any other test
has a negative score. I believe that Cookies are not extra credit, but some
others shown in your results are.

Since you previously scored 105/100 just a few months ago, at that time you
wouldn’t have had the two negative scores shown for your site today: CSP
unsafe-eval, and insecure JavaScript external resources. Since you’ve
recently made changes, it seems very possible that those changes have
introduced these two penalties. I encourage working to understand and
address them, as that will restore your scoring to the A+ you’re hoping to
reach.

I previously explained how to repair the insecure JS -5 penalty. For the
unsafe-eval penalty, investigating why ‘unsafe-eval’ was added to your
site’s CSP headers would be useful; either it’s unnecessary/accidental and
it can be removed, or it’s become necessary for some change you’ve made,
and the lower score for your site will reflect that it’s less safe if you
decide to keep that change regardless. (I don’t have context for why this
change was made, so I can’t say which of these is the case.)

**Comment by mktl73** [comment]
I can confirm that nothing changed on our side and we always had -10 on CSP.
![score](https://user-images.githubusercontent.com/64254866/80207037-bb2a8e00-862d-11ea-9c9a-14aace3986fe.jpg)
We check our web sites on regular basis and this is the first time we notice a decrease in the score and the rating so I still believe something change on the test platform.
However, I just saw that "Bonus points are only awarded if the site's score without them is 90 (A) or greater". The only explanation is that something changed on the SRI test as this is now seen as "failed (-5)"
![sri](https://user-images.githubusercontent.com/64254866/80208178-f332d080-862f-11ea-8b95-dd160b02ca55.JPG)

**Comment by floatingatoll** [comment]
The piwik.js code you're using is written to create <script src=//>
elements rather than <script src=https://> elements at various stages —
both at the initial header of your page where it runs, and deeper on in the
piwik.js code. I don't think the Observatory can see that, but it would
assign a score penalty if it could. (The piwik code is also conflicting
with your CSP header, I believe.)

I misread the error last night and found the issue that the Observatory
*can* see today. It's this external include without a hashed checksum
that's causing the -5 penalty:

src=https://portal.nsv.eurocontrol.int/main.js

If you control both www and portal.nsv, then you can probably set aside the
score warning as you know (which the Observatory cannot) that the offsite
resource is your own.
