### ISSUE TITLE
Fails to Detect HTTPS Redirect

### ISSUE THREAD

**Issue by joshvickerson** [mozilla/http-observatory-website#25]
In testing my own website, joshvickerson.com, Observatory indicates that my site doesn't support https. However, the site is configured to require https. If you visit in a browser, you will be redirected to https://www.joshvickerson.com every time.

**Edit: This occurs when I simply enter joshvickerson.com as the domain. If I enter www.joshvickerson.com as the domain, it does detect HTTPS support. Is this an issue with Observatory, my configuration, or both?**

**Comment by edmorley** [comment]
This is because the non-www site isn't available over HTTPS, ie:
```bash
$ curl -I --connect-timeout 5 https://joshvickerson.com
curl: (28) Connection timed out after 5000 milliseconds
```

This tool checks the domain name entered (joshvickerson.com), not the domain it redirects to (www.joshvickerson.com).

If you instead test the www domain, the tool reports HTTPS support:
https://mozilla.github.io/http-observatory-website/analyze.html?host=www.joshvickerson.com

Note that in this case, since the redirect is to another domain, it means that HSTS (if it were served from https://www.joshvickerson.com , which it currently isn't) will still never be set for joshvickerson.com, meaning users who bookmark/link/type joshvickerson.com manually are not protected from MITM.

@marumari will no doubt be able to recommend best practice here (double redirect - once to https://joshvickerson.com that sets HSTS on the top-level domain with `includeSubdomains` set, and then another redirect to https://www.joshvickerson.com perhaps ?)

**Comment by joshvickerson** [comment]
Ah, okay. My HTTPS implementation is a bit naive, I think. I just set it up with LetsEncrypt and told it to require HTTPS and left it at that. Thanks for such a helpful explanation! I'd greatly appreciate recommendations on how to improve my configuration.

**Comment by marumari** [comment]
Yep, you should have HTTPS setup on both the root domain *and* www.

The correct way to set things up with HTTPS and redirections is to redirect like this:

http://joshvickerson.com/ -> https://joshvickerson.com/ (this sets HSTS) -> https://www.joshvickerson.com/

Set things up in that manner and you should pass the HTTPS, HSTS, and Redirection tests.  :)

**Comment by joshvickerson** [comment]
As noted before, I set this up with LetsEncrypt so I'm not really sure how a HTTPS setup actually works. How would I go about setting up that chain? Would that be just editing my DNS records or is there more to it than that?

And further sounding like an idiot, what is HSTS?

**Comment by marumari** [comment]
The redirection would be part of your web server configuration.  For example, if you use nginx, it would look like this:

```nginx
# Redirect all HTTP requests to HTTPS with a 301 Moved Permanently response.
return 301 https://$host$request_uri;
```

HSTS is HTTP Strict Transport Security:
https://wiki.mozilla.org/Security/Guidelines/Web_Security#HTTP_Strict_Transport_Security

Anyways, I'm going to go ahead and close this bug, but feel free ask more questions if you run into trouble.
