### ISSUE TITLE
Characters deleted out of URL field

### ISSUE THREAD

**Issue by planeflyer1000** [mozilla/http-observatory-website#274]
When I attempt to scan some of our sites, it'll return an error "XXXXXXXXX is an invalid hostname"

the character that is deleted is a "-" 

an example would be "X-XXXXX.XXXX.XXXX.XXX"

it is reflected in the red error box as missing the -

**Comment by Harsh3363** [comment]
can u be more specific about the bug please

**Comment by planeflyer1000** [comment]
Harsh,

When I enter certain urls it won't scan and return an error of the hostname with the - left out

For example

https://j-klondike.gran.gov

mozilla observatory will return with an error that says "invalid hostname" and display

j klondike.gran.gov as the url

it looks like mozilla observatory might be parsing out the - after one letter. Other URLs with - in them work fine. But those that have one letter and then a - seem to fail.

**Comment by gene1wood** [comment]
It appears that https://j-klondike.gran.gov/ is no longer available. Is there another site you can think of that manifests this `-` issue?

When I try a site with a dash in the domain name like `penny-arade.com` it works : https://observatory.mozilla.org/analyze/penny-arcade.com

This isn't a perfect match to your example because I'd need something like `this-has-a-dash.example.com`

**Comment by gene1wood** [comment]
If someone can provide an example site that can reproduce this issue, please feel free to open a new issue and mention that site.
