### ISSUE TITLE
Avoid leaking information about hidden scans

### ISSUE THREAD

**Issue by BenBE** [mozilla/http-observatory-website#34]
The API should avoid leaking information about scans marked as hidden.

Currently simply iterating over certain objects reveals information that basically contain the originally requested domain. No proper access restriction (like including the domain for which that test object is valid) is present.

**Comment by marumari** [comment]
Ahh, yes.  The scans are sequential, and "hidden" is only meant to keep them from the homepage, not keep them secret.  I may implement a "secret" scan in the future, but this is basically working as intended.  If it's truly important to keep your domain secret, then it's recommended to download your own instance of the observatory and scan with that.

I'm going to leave this open though, because it is a good thing to add to the FAQ.  Thanks!

**Comment by marumari** [comment]
I've gone ahead and updated the FAQ to address what "hidden" scans actually are.  Thanks for bringing this to my attention!
