### ISSUE TITLE
Observatory wants 26 weeks for HSTS headers, preload list only needs 18

### ISSUE THREAD

**Issue by steveworkman** [mozilla/http-observatory-website#54]
This is more a question on the ratings, rather than the site itself - the test for yell.com (https://observatory.mozilla.org/analyze.html?host=yell.com) got a -10 on its HSTS for "HTTP Strict Transport Security (HSTS) header set to less than six months (15768000)"

I've got it set to 18 weeks, not 26 as the HSTS preload submission site only needs the header set to 18 weeks in order to meet their requirements.

In general, longer is better, but I'd have thought 18 weeks is enough time for a header like that.

Can you explain why 26 weeks, not 18 weeks?

**Comment by marumari** [comment]
Okay, so there are a bunch of things going on here.  One is that the Observatory actually lies -- it says it wants 15768000, but it actually is really only looking for 15552000 (26 weeks, I believe).  It says 1576800 because it looks prettier.  ;)  A lot of that is based on the most common values seen in the top million sites:

https://gist.github.com/marumari/0d88fce62fa8a860d14b4a33dcf74a17

Setting it at 15552000 internally meets the HSTS values used by some 95% or so of the top million sites that use HSTS.

And you're probably right that 18 weeks is long enough, but no matter where you set the requirement, people will always question it.  I mean, if 18 weeks is long enough, how about 16 weeks, and so on.

So anyways, that's a long winded way of that we're probably not going to change it.  😀   Is there a technical reason why it can be increased from 18 weeks to six months? If you've been operating at 18 weeks without issue, increasing it by 50% or so probably shouldn't break anything.

**Comment by steveworkman** [comment]
Sure, we can increase it, and that's not a problem - I'm more thinking that advice from one prominent site doesn't match advice from another. If we fix that, I think we can fix the whole internet!

I'd be happy upping the timeout - doing that we should get @lgarron to up the preload list one as well

**Comment by marumari** [comment]
I know that @lgarron has in the past said that the example provided is only meant to be used as an example and is not meant to be considered a recommendation.  That said, people will definitely use it that way.

Here is my proposal for @lgarron: leave the minimum requirement as it is (18 weeks) because it's painful to change requirements, but update the sample to be:

`Strict-Transport-Security: max-age=15768000; includeSubDomains; preload`

@lgarron, what do you think?

**Comment by lgarron** [comment]
> I know that @lgarron has in the past said that the example provided is only meant to be used as an example and is not meant to be considered a recommendation. That said, people will definitely use it that way.

Very definitely. It's intentionally not displayed as "advice" or a "recommendation".

> @lgarron, what do you think?

I think people will shoot themselves in the foot no matter what we do. :-/
I guess since it's only an "example", I could totally just raise it.

> I'm more thinking that advice from one prominent site doesn't match advice from another. If we fix that, I think we can fix the whole internet!

:-!
We [haven't](https://crbug.com/626180) [even](https://crbug.com/591212) [fixed]([608599](https://crbug.com/608599) **[Assigned]** Collect data to help determine a pruning policy for the HSTS preload list) [HSTS]([587954](https://crbug.com/587954) **[Started]** ☂ HSTS Preload List: Address Growing Pains). :-P

I think it's great for the Observatory to ask for half a year as best practice. If we needed to agree on a standard, I think either half a year or a year would be good. (Actually, just over a year sounds great for sites you might only visit during a certain time of the year.)

But I don't want to do it "just 'cause". What are your actual concerns with different values in "advice" across the internet?

**Comment by lgarron** [comment]
On a related note, I believe Firefox used to have issues with their HSTS header liveness data timing out around the end of a stable release cycle. Is that still an issue, and how high would be a comfortable margin?

**Comment by marumari** [comment]
In the Mozilla Web Security guidelines, we recommend a year:
https://wiki.mozilla.org/Security/Guidelines/Web_Security#HTTP_Strict_Transport_Security

And that's what I would have set the Observatory to, but so many sites fell under it due to tons of random StackExchange and blog posts recommending less than that.  I set it to 26 weeks just so that I didn't get too many complaints.

So how leaving the minimum requirement at 18 weeks, and changing the example given to what we recommend in our guidelines:

`Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`

**Comment by lgarron** [comment]
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload

Just asked @agl, and he didn't have objections.

I [await your PR](https://github.com/chromium/hstspreload.appspot.com/blob/2445cdc9d68a701166dc817247b5e76a5e3e5dbb/frontend/index.html#L127). ;-)

**Comment by lgarron** [comment]
> And that's what I would have set the Observatory to, but so many sites fell under it due to tons of random StackExchange and blog posts recommending less than that. I set it to 26 weeks just so that I didn't get too many complaints.

Your move. ;-)

**Comment by marumari** [comment]
Looks like the hstspreload.appspot.com code has been updated to a year in an their example, which would totally meet the Observatory's minimum requirement.  Closing this one out then.  :)

**Comment by steveworkman** [comment]
Awesome - thank you @lgarron & @marumari - I'll get my headers updated

**Comment by lgarron** [comment]
See https://github.com/chromium/hstspreload.appspot.com/issues/62 for thoughts about adding explicit recommendations to hstspreload.appspot.com
