### ISSUE TITLE
HSTS preload for subdomains

### ISSUE THREAD

**Issue by Fleshgrinder** [mozilla/http-observatory-website#64]
Submitting a subdomain to the preload list is actually not possible and the HSTS header **must** contain `includeSubDomains` in order to be included in the preloading list. However, one might still use `www.example.com` instead of `example.com` for the website for cookie security. The thing is that the when one submits `www.example.com` to the Observatory it will forward the domain name as is to the HSTS app and report that it is not being preloaded although it might be if only the hostname with TLD would be forwarded.

Extracting the hostname with TLD from the given domain name is trivial with the [public suffix list](https://publicsuffix.org/) and should cover 99% of all cases and results in proper preloading reports.

**Comment by marumari** [comment]
This is an expected and designed behavior, one because I didn't want to deal with all the PSL stuff (I already do in the backend scanner and it's a surprising pain in Python, let alone JavaScript), and also because there are certainly exceptions to that rule:

https://hstspreload.appspot.com/?domain=bugzilla.mozilla.org
https://observatory.mozilla.org/analyze.html?host=bugzilla.mozilla.org

Thank you for submitting the bug though!

**Comment by Fleshgrinder** [comment]
Okay, thanks for pointing out the exceptional case.

**Comment by marumari** [comment]
If you are interested in integrating the PSL and writing the JavaScript code, I would be happy to merge it.  It's just really complicated for a relatively low impact thing.

Probably the best way to do it would be to open an enhancement in the hstspreload github to allow us to send a flag like checkRootDomain=true.  I'd be happy to implement it in that case.

Thanks again!
